ALTER TABLE  Locations ADD PRIMARY KEY (LocationID);

ALTER TABLE Users ADD PRIMARY KEY (UserID);

ALTER TABLE Roles ADD PRIMARY KEY (RolesID);

ALTER TABLE Taverns ADD PRIMARY KEY (TavernID);
ALTER TABLE Taverns ADD FOREIGN KEY (UserID) REFERENCES Users;
ALTER TABLE Taverns ADD FOREIGN KEY (LocationID) REFERENCES Locations;

DROP TABLE Rats;

ALTER TABLE UserRoles ADD FOREIGN KEY (UserID) REFERENCES Users;
ALTER TABLE UserRoles ADD FOREIGN KEY (RoleID) REFERENCES Roles;