SELECT DISTINCT CONCAT('CREATE TABLE', ' ', TABLE_NAME, ' (') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Taverns'
UNION ALL
SELECT CONCAT(COLUMN_NAME, ' ', DATA_TYPE, ',') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Taverns'
UNION ALL
SELECT DISTINCT ')' FROM INFORMATION_SCHEMA.COLUMNS
